# D A N G E R - Read it, please!
#
# If the event is from pull_request_target, it must checked by a VTEX person,
# if you think it's safe, you have to add label 'safe to test' to run SonarCloud.
#
# You MUST only give this label if there's NO CHANGES on WORKFLOWS.
#
# This is important to avoid been hacked.

name: '[QE] SonarCloud'

on:

  # Trigger when the master is updated
  push:
    branches:
    - master
    - main
    - bugfix/*
    - chore/*
    - enhancement/*
    - feature/*
    - fix/*
    - hotfix/*
   
  # Trigger after label approval
  pull_request_target:
    branches:
    - master
    - main
    types:
    - labeled
    - opened
    - edited
    - reopened
    - syncronize

jobs:

  # Job for SonarCloud analysis
  # You must set the right SONAR_TOKEN token on your secrets
  sonarcloud:
  
    name: SonarCloud
    runs-on: ubuntu-latest
        
    # Don't allow code changes from Workflows
    permissions:
      contents: read
    
    # Only run if it's PUSH or has 'safe to test' label
    if: ${{ github.event_name == 'push' ||
            ( 
              github.event_name == 'pull_request_target' &&
              contains(github.event.label.name, 'safe to test')
            )
         }}
    
    steps:
    
    # Checkout the PR code
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
        ref: ${{ github.event.pull_request.head.sha }}

    # If cache exist, use it; if don't, create it
    - name: Cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    # Install base folder
    - name: Install main app dependencies
      run: yarn
      if: steps.cache-node-modules.outputs.cache-hit != 'true'

    # Install Node dependencies
    - name: Install node app dependencies
      run: yarn
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      working-directory: ./node

    # Install React dependencies
    - name: Install react app dependencies
      run: yarn
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      working-directory: ./react

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
          # SonarCloud doesn't treat pull_request_target, so we need this
          args: >
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} 
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} 
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }} 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
